VPATH = ../SPECS
TOOLSPEC = tools-binutils-pass-1.spec tools-gcc-pass-1.spec tools-linux-api-headers.spec \
		tools-glibc.spec tools-libstdc.spec tools-binutils-pass-2.spec \
		tools-gcc-pass-2.spec tools-tcl.spec tools-expect.spec tools-dejagnu.spec \
		tools-m4.spec tools-ncurses.spec tools-bash.spec tools-bison.spec \
		tools-bzip2.spec tools-coreutils.spec tools-diffutils.spec tools-file.spec \
		tools-findutils.spec tools-gawk.spec tools-gettext.spec tools-grep.spec \
		tools-gzip.spec tools-make.spec tools-patch.spec tools-perl.spec \
		tools-python.spec tools-sed.spec tools-tar.spec tools-texinfo.spec \
		tools-xz.spec tools-zlib.spec tools-popt.spec tools-openssl.spec \
		tools-libelf.spec tools-rpm.spec tools-sudo.spec
all: $(TOOLSPEC)
tools-linux-api-headers.spec:	tools-linux-api-headers
	@../mk-spec.sh tools-linux-api-headers
tools-binutils-pass-1.spec: tools-binutils-pass-1
	@../mk-spec.sh tools-binutils-pass-1
tools-gcc-pass-1.spec : tools-gcc-pass-1
	@../mk-spec.sh tools-gcc-pass-1
tools-glibc.spec: tools-glibc
	@../mk-spec.sh tools-glibc
tools-libstdc.spec: tools-libstdc
	@../mk-spec.sh tools-libstdc
tools-binutils-pass-2.spec: tools-binutils-pass-2
	@../mk-spec.sh tools-binutils-pass-2
tools-gcc-pass-2.spec: tools-gcc-pass-2
	@../mk-spec.sh  tools-gcc-pass-2
tools-tcl.spec: tools-tcl
	@../mk-spec.sh tools-tcl
tools-expect.spec: tools-expect
	@../mk-spec.sh tools-expect
tools-dejagnu.spec: tools-dejagnu
	@../mk-spec.sh tools-dejagnu
tools-m4.spec: tools-m4
	@../mk-spec.sh tools-m4
tools-ncurses.spec: tools-ncurses
	@../mk-spec.sh tools-ncurses
tools-bash.spec: tools-bash
	@../mk-spec.sh tools-bash
tools-bison.spec: tools-bison
	@../mk-spec.sh tools-bison
tools-bzip2.spec: tools-bzip2
	@../mk-spec.sh tools-bzip2
tools-coreutils.spec: tools-coreutils
	@../mk-spec.sh tools-coreutils
tools-diffutils.spec: tools-diffutils
	@../mk-spec.sh tools-diffutils
tools-file.spec: tools-file
	@../mk-spec.sh tools-file
tools-findutils.spec: tools-findutils
	@../mk-spec.sh tools-findutils
tools-gawk.spec: tools-gawk
	@../mk-spec.sh tools-gawk
tools-gettext.spec: tools-gettext
	@../mk-spec.sh tools-gettext
tools-grep.spec: tools-grep
	@../mk-spec.sh tools-grep
tools-gzip.spec: tools-gzip
	@../mk-spec.sh tools-gzip
tools-make.spec: tools-make
	@../mk-spec.sh tools-make
tools-patch.spec: tools-patch
	@../mk-spec.sh tools-patch
tools-perl.spec: tools-perl
	@../mk-spec.sh tools-perl
tools-python.spec: tools-python
	@../mk-spec.sh tools-python
tools-sed.spec: tools-sed
	@../mk-spec.sh tools-sed
tools-tar.spec: tools-tar
	@../mk-spec.sh tools-tar
tools-texinfo.spec: tools-texinfo
	@../mk-spec.sh tools-texinfo
tools-xz.spec: tools-xz
	@../mk-spec.sh tools-xz
tools-zlib.spec: tools-zlib
	@../mk-spec.sh tools-zlib
tools-popt.spec: tools-popt
	@../mk-spec.sh tools-popt
tools-openssl.spec: tools-openssl
	@../mk-spec.sh tools-openssl
tools-libelf.spec: tools-libelf
	@../mk-spec.sh tools-libelf
tools-rpm.spec: tools-rpm
	@../mk-spec.sh tools-rpm
tools-sudo.spec: tools-sudo
	@../mk-spec.sh tools-sudo
